### ISSUE TITLE
"Automatically Follow Redirects" setting per API Case level does not work within Test Cases

### ISSUE THREAD

**Issue by vzts** [apidog/apidog-support#18]
First of all, I love your product so much. Thank you for making this dream product come true!

I found out one issue that
"Automatically Follow Redirects" setting per API Case level (Case 1) does not work within Test Cases,
while "Automatically Follow Redirects" setting in global (Case 2) works within Test Cases.

Case 1:
![스크린샷 2023-05-19 오후 1 48 37](https://github.com/apidog/apidog-support/assets/27868171/0be5ab12-8fdd-43ba-87b0-105295eb3eb1)
![스크린샷 2023-05-19 오후 1 45 45](https://github.com/apidog/apidog-support/assets/27868171/7a7dc3fe-fc71-4025-98d5-18ba6fae2629)

Case 2:
![스크린샷 2023-05-19 오후 1 45 56](https://github.com/apidog/apidog-support/assets/27868171/dfac06e3-5701-4f93-9167-09e8354c23dc)
![스크린샷 2023-05-19 오후 1 46 02](https://github.com/apidog/apidog-support/assets/27868171/a491596e-592a-4d82-8343-344f493524bf)

**Comment by YukioIkeda** [comment]
This bug is fixed in the recent version. Thanks for your issue.
